name: latest_main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  latest_main:
    name: "latest"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: latest_main
        shell: pwsh
        run: |
          ./entrypoint.ps1 latest_main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
