name: pr_main
on:
  push:
    branches-ignore:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  pr_main:
    name: "pr_main"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: pr_main
        shell: pwsh
        run: |
          ./entrypoint.ps1 pr_main
